# Generated by Django 5.1.2 on 2024-10-18 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collection", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gamer",
            options={"verbose_name": "Gamer", "verbose_name_plural": "Gamers"},
        ),
        migrations.RenameField(
            model_name="game",
            old_name="release_year",
            new_name="release_date",
        ),
        migrations.AlterField(
            model_name="collection",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
