# Generated by Django 5.1.2 on 2024-10-20 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collection", "0002_alter_gamer_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamer",
            name="bio",
            field=models.TextField(blank=True),
        ),
    ]
